<a href="https://colab.research.google.com/github/raissaazaria/DataScience/blob/main/Week_6_Forum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import metrics
import numpy as np
from sklearn.metrics import accuracy_score

In [20]:
df = pd.read_csv("Starbucks_satisfactory_survey_encode_cleaned.csv")

In [21]:
conditions = [df["timeSpend"] >= 2, (df["timeSpend"] < 2) & (df["timeSpend"] > 0), df["timeSpend"] <= 0]
choices = ['high', 'average', 'low']
df['length'] = np.select(conditions, choices, default = np.nan)

df

,Id,gender,age,status,income,visitNo,method,timeSpend,location,membershipCard,...,promoMethodApp,promoMethodSoc,promoMethodEmail,promoMethodDeal,promoMethodFriend,promoMethodDisplay,promoMethodBillboard,promoMethodOthers,loyal,length
0,1,1,1,0,0,3,0,1,0,0,...,1,1,1,1,1,1,1,1,0,average
1,2,1,1,0,0,3,2,0,1,0,...,1,1,1,1,1,1,1,1,0,low
2,3,0,1,2,0,2,0,1,2,0,...,1,1,1,1,1,1,1,1,0,average
3,4,1,1,0,0,3,2,0,2,1,...,1,1,1,1,1,1,1,1,1,low
4,5,0,1,0,0,2,2,1,1,1,...,1,1,1,1,1,1,1,1,0,average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,118,0,3,1,1,2,0,2,1,0,...,1,1,1,1,1,1,1,1,0,high
109,119,0,1,2,0,2,0,2,1,0,...,1,1,1,1,1,1,1,1,0,high
110,120,0,1,0,0,3,0,1,1,1,...,1,1,1,1,1,1,1,1,1,average
111,121,1,1,2,0,3,2,0,0,1,...,1,1,1,1,1,1,1,1,0,low
112,122,0,1,2,2,3,0,1,1,1,...,1,1,1,1,1,1,1,1,1,average

In [22]:
feature = ["gender"]
x = df[feature]
y = df["timeSpend"]

In [26]:
svm = SVC(kernel='rbf', random_state = 1, gamma= 2, C=1)

svm.fit(x,y)

y_pred = svm.predict(x)
print(accuracy_score(y, y_pred))

0.6371681415929203

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)